In [1]:
# This script contains exercises on 
# manipulating arrays with numpy
import numpy as np
x = np.arange(0, 3**3)

#### 1. What is the length of x?

In [2]:
len(x)

27

#### 2. How do you get the first value out of x?

In [3]:
print(x[0])

0


#### 3. How do you get the last value out of x?

In [6]:
print(x[-1])

26


#### 4. How do you get the first 5 values out of x?

In [9]:
print (x[0:5])

[0 1 2 3 4]


#### 5. What about the last 5 values of x?

In [14]:
print(x[-5:])

[22 23 24 25 26]


#### 6. How do you get every other value out of x?

In [16]:
start = 2
stop = 26
step = 2
print(x[start:stop:step])

[ 2  4  6  8 10 12 14 16 18 20 22 24]



#### 7. Get the first 9 values of x, and reshape them to a 3x3 matrix. Assign this matrix to the variable `y`

In [19]:
y = x[:9].reshape(3, 3)
print(y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 8. How do you get the middle value out of y?

In [20]:
y = np.array([
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8],
])
print(y[1,1])

4


#### 9. How do you get the first row out of y?

In [21]:
print (y[0,:])

[0 1 2]


#### 10. How do you get the first column out of y?

In [23]:
print(y[:,0])

[0 3 6]


#### 11. Reshape x into a 3x3x3 cube. Assign this to the variable `z`

In [24]:
x = np.arange(0, 3**3)
z = x.reshape(3, 3, 3)
print(z)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


#### 12. How do you get the "center" value from z?

In [26]:
z = np.array([
    [[ 0, 1, 2],
     [ 3, 4, 5],
     [ 6, 7, 8]],
    [[ 9,10,11],
     [12,13,14],
     [15,16,17]],
    [[18,19,20],
     [21,22,23],
     [24,25,26]]
])
print(z[1, 1, 1])

13



#### 13. How do you take the total sum of z?

In [29]:
print(z.sum())

351



#### 14. How do you take the sum along the first dimension of z?

In [32]:
print(z.sum(axis=0))

[[27 30 33]
 [36 39 42]
 [45 48 51]]


#### 15. How do you take the sum along the last dimension of z?

In [35]:
print(z.sum(axis=2))

[[ 3 12 21]
 [30 39 48]
 [57 66 75]]
